config/routes.rb
Rails.application.routes.draw do
  resources :vendors
  resources :sweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sweet.rb
class Sweet < ApplicationRecord
  belongs_to :vendor
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :sweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dummy_name_controller.rb
class DummyNameController < ApplicationController
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController

  def index
    @sweets = Sweet.find(sweet_params[:id])
  end

  def show
    @sweet = Sweet.find(sweet_params[:id])
  end

  private

  def sweet_params
    params.permit(:name, :id)
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  def index
    @vendors = Vendor.all
  end

  def show
    @vendor = Vendor.find(vendor_params[:id])
  end

  private

  def vendor_params
    params.permit(:name, :id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dummy_name_helper.rb
module DummyNameHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsImmersiveAssessmentAlternateFirstRound</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sweets/index.html.erb
<h3> Sweets Index </h3>
<%= @sweets.each do |s| %>
  <h3><%= link_to s.name, sweet_path(v) %></h3>

<% end %>

app/views/sweets/show.html.erb
<h3> Show sweet </h3>
<%= @sweet.name %>

app/views/vendors/index.html.erb
<h3> vendors Index </h3>
<%= @vendors.each do |v| %>
  <h3><%= link_to v.name, vendor_path(v) %></h3>

<% end %>

app/views/vendors/show.html.erb
<h3> Show Vendor </h3>
<%= @vendor.name %>